#define VOID 1
#define INTEGER 2
#define DOUBLE 3
#define BOOL 4
#define STRING 5
#define CLASS 6
#define INTERFACE 7
#define NULL 8
#define THIS 9
#define EXTENDS 10
#define IMPLEMENTS 11
#define FOR 12
#define WHILE 13
#define IF 14
#define ELSE 15
#define RETURN 16
#define BREAK 17
#define NEW 18
#define NEWARRAY 19
#define PRINT 20
#define READINTEGER 21
#define READLINE 22
#define TRUE 23
#define FALSE 24
#define ID 25
#define OPERATOR 26
